### ISSUE TITLE
System.AccessViolationException: 

### ISSUE THREAD

**Issue by Varmod** [jbaarssen/PdfLibCore#17] opened 2023-04-05 15:31 UTC
Hi, I have a simple avalonia window where I load a multi page pdf and provide some simple navigation. I only show one page at a time so there's a button to load the next/previous page. 

However after a few clicks to the next page I crash with a: 
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.' 
from: pdfPage.Render(bitmap, PageOrientations.Normal, RenderingFlags.LcdText);

I'm using the newest 2.4 version of the plugin.

**Comment by Kokenberg** [comment] 2023-04-05 16:39
When does this occur? Do you run your build in debug or release mode? I've seen a couple of Access violation exceptions when running in Debug mode, but in Release mode all is fine. It seems that we are missing a closure of a handle somewhere which seems, as far as I have seen, is only an issue in Debug.

**Comment by Varmod** [comment] 2023-04-06 06:59
It occurs both in debug and release, however in release it occurs way less. 
In debug it usually crashes in around 10 pages or so.
In release it took me over 140 to crash it.

**Comment by dellos** [comment] 2023-04-07 02:29
Hi, is that the same error as this closed Issue?
[https://github.com/jbaarssen/PdfLibCore/issues/14#issue-1507136105] -> my report
if yes, I guess that the updated [bblanchon] version still does not fix this bug.
I am facing the same problem with [pdfPage.Render(bitmap, PageOrientations.Normal, RenderingFlags.GrayScale);] too.
I guess that [bitmap] was allocated in unsafe memory or failed to release.

**Comment by Varmod** [comment] 2023-04-07 18:15
yes it’s the same one. Sadly I’m not able to catch the exception so it’s a pretty serious issue

**Comment by Kokenberg** [comment] 2023-04-08 12:22
I'm going to investigate this a bit further.

**Comment by Kokenberg** [comment] 2023-04-08 14:05
I've created a new branch [(feature/AccessViolationException)](https://github.com/jbaarssen/PdfLibCore/tree/feature/AccessViolationException). In the branch I've updated the ExampleApp, it will asynchronously extract images from a couple of PDF files, one of which contains over 600 pages. 

I've run the example app both in debug and release mode and I cannot get it to throw an AccessViolationException.

@Varmod and/or @dellos if either of you has  an example application which does throw the exception I would like to look at it.

**Comment by dellos** [comment] 2023-04-10 02:51
@Kokenberg , Hi , I created a simple Console project with can run into AccessViolationException.
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/5093271/230815351-b6617d9c-2bed-4c63-94f8-31ddeff4855f.png">

Testing Resource is private files, so may I push it in GitHub and Invite you?
Used VS2019, .NetCore3.1 , PdfLibCore 2.3.0, And System.Drawing.Common 5.0.3 .

PS1: Invite sent
PS2: I try to Wrap bitmap into a "using" block but same no difference.
PS3: use PdfLibCore 2.4.0 I can sometimes run 10 rounds before it crash. Please reference to below scene shot
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/5093271/230826984-7b38009d-b5c3-41ae-a878-a805cfb5b987.png">
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/5093271/230827366-c17acf8d-1084-40ee-a0af-beb45fda870f.png">

**Comment by Kokenberg** [comment] 2023-04-10 11:23
Hi @dellos,

I've updated your code just a tiny bit and upgraded PdfLibCore to version 2.4.0
![image](https://user-images.githubusercontent.com/15146247/230892247-d8c96b6a-c848-480b-b896-0122d3c8154e.png)
I've ran your application for a while and stopped around run 43 without any issues...
Using version 2.3.0 did throw AccessViolationExceptions, around the 4th or 6th run.

Btw, you do know that the TIFF images you create are around 100Mb each? Is there a reason to create such large images?

![image](https://user-images.githubusercontent.com/15146247/230893258-91d2f608-33fb-4dcb-818a-c43e42e65c55.png)

Another, small side note, the large amount of memory used is due to the very high DPI you are using. That high DPI also results in 'extremely' large files.
![image](https://user-images.githubusercontent.com/15146247/230894712-7a1243ed-e626-475a-9058-8c40f432c6a7.png)
![image](https://user-images.githubusercontent.com/15146247/230894754-24ecbd5c-526a-4c2f-ad24-d6f69a15e584.png)

**Comment by dellos** [comment] 2023-04-12 16:51
Hi, thank you for taking the time to help me figure out some points.

1. There is PdfLibCore.ImageSharp Nutget Package.
2. I checked my code(before your commit) and tried to run with PdfLibCore.ImageSharp(2.4.0) and still get AccessViolationException error.
3. The main difference here is your committed code uses the Image class of SixLabors.ImageSharp lib, and my code uses the Image class of System.Drawing.Common lib.
So, I think the main point here is "Don't use System.Drawing.Common with PdfLibcore"
4. I still don't know some how use img.SaveAsTiffAsync(result) of SixLabors.ImageSharp make created image size too big (around 100Mb). The same parameters if I use img.Save(result,ImageFormat.Tif) of  System.Drawing.Common the image size is just around 1.3 MB!!!.
PS:=>I can confirm that your code below run without crashing (tested about 26 rounds )


`using SixLabors.ImageSharp;`
```
        private const double DpiX = 600D;
        private const double DpiY = 600D;   
```
 
        public async Task<string> PdfToImageAsync(string pdf, string folder, string ext = ".tif")
        {
            var result = Path.Combine(folder, Path.GetFileNameWithoutExtension(pdf), $"{Path.GetFileNameWithoutExtension(pdf)}_{Path.GetRandomFileName()}{ext}");
            Directory.CreateDirectory(Path.Combine(folder, Path.GetFileNameWithoutExtension(pdf)));

            try
            {
                await using var fs = File.OpenRead(pdf);
                using var pdfDocument = new PdfDocument(fs);
                using var page = pdfDocument.Pages[0]; // should one page pdf file
                using var bitmap = new PdfiumBitmap(
                    (int) (DpiX * page.Size.Width / 72),
                    (int) (DpiY * page.Size.Height / 72),
                    false);
                page.Render(bitmap, PageOrientations.Normal, RenderingFlags.Grayscale);
                await using var stream = bitmap.AsBmpStream(DpiX, DpiY);
                using var img = await Image.LoadAsync(stream);
                await img.SaveAsTiffAsync(result);
            }
            catch (Exception e)
            {
                Console.WriteLine($"{pdf} {e.Message}");
                throw;
            }
            return result;
        }

**Comment by Kokenberg** [comment] 2023-04-12 16:56
@dellos,

Glad to hear it's working now for you as well. Yes, we've created a number of 'extra' NuGet packages for different image libraries (like ImageSharp) mainly because PDFLibCore is cross platform. 

By lowering your DPI (from 600DPI to 300DPI) should drastically lower the filesize and increase speed.

> The industry standard for quality photographs and image is typically 300dpi. For businesses, producing an external document like a brochure, a booklet, or a flyer requires 300dpi. You might be able to get away with 250dpi if you are less concerned with the quality and resolution of the printing. (https://www.dme.us.com/2018/12/11/what-is-dpi-and-what-are-the-requirements-for-different-industries/#:~:text=The%20industry%20standard%20for%20quality,and%20resolution%20of%20the%20printing.)

**Comment by Kokenberg** [comment] 2023-04-12 16:57
If you feel that this 'solves' your issue, you may close this issue.

**Closed as completed** 2023-04-14 13:17 UTC
